package fr.istic.tools.scanexam.instances;

import fr.istic.tools.scanexam.Exam;
import fr.istic.tools.scanexam.Question;
import fr.istic.tools.scanexam.instances.ExamIO;
import fr.istic.tools.scanexam.utils.ScanExamXtendFactory;
import java.util.Collections;
import java.util.List;
import org.eclipse.xtext.xbase.lib.CollectionLiterals;
import org.eclipse.xtext.xbase.lib.Exceptions;
import org.eclipse.xtext.xbase.lib.ExclusiveRange;

@SuppressWarnings("all")
public class PFOExams {
  public static Exam olivier() {
    Exam _xblockexpression = null;
    {
      final int X0 = 100;
      final int X1 = 2450;
      final List<String> students = Collections.<String>unmodifiableList(CollectionLiterals.<String>newArrayList("ALLA Haphet", "ARQUES Alexandre", "BONNEAU Quentin", "CHEVALIER Michel", "CHILLET Alice", "DE TAEYE Caroline", "DELPORTE Kevin", "DENES PIERRE", "DUPIN Lucas", "ETRILLARD Olivier", "GUILBAUD Valentin", "KLEIN Nicolas", "LASSOUT Leo", "LE PERON-SLAES Alix", "MAITRE Kilian", "MALHERBE Tom", "MANDELLI Zoe", "MOLLARD Arnaud", "MROUEH Celia", "NADAL Sophie", "PLUMIER Quentin", "POULLOT Amelie", "ROGER Benoit-Joseph", "SCIASCIA Hugo", "SOURY Theo", "THUILLIER Corentyn", "THURA Remy", "TOURTEAU Remy", "TURBAULT Adrien", "UMENHOVER Lola"));
      Question _question = ScanExamXtendFactory.question("NAME", Collections.<Integer>unmodifiableList(CollectionLiterals.<Integer>newArrayList(Integer.valueOf(X0), Integer.valueOf(0), Integer.valueOf(X1), Integer.valueOf(800), Integer.valueOf(1))), Collections.<Integer>unmodifiableList(CollectionLiterals.<Integer>newArrayList(Integer.valueOf(30), Integer.valueOf(80), Integer.valueOf(80), Integer.valueOf(60), Integer.valueOf(0))), students, 0);
      Question _question_1 = ScanExamXtendFactory.question("EX1_Q1", Collections.<Integer>unmodifiableList(CollectionLiterals.<Integer>newArrayList(Integer.valueOf(X0), Integer.valueOf(1200), Integer.valueOf(X1), Integer.valueOf(2900), Integer.valueOf(1))), Collections.<Integer>unmodifiableList(CollectionLiterals.<Integer>newArrayList(Integer.valueOf(30), Integer.valueOf(80), Integer.valueOf(80), Integer.valueOf(60), Integer.valueOf(0))), Collections.<String>unmodifiableList(CollectionLiterals.<String>newArrayList("A", "B", "C", "D", "E", "F")), 2);
      Question _question_2 = ScanExamXtendFactory.question("EX1_Q2", Collections.<Integer>unmodifiableList(CollectionLiterals.<Integer>newArrayList(Integer.valueOf(X0), Integer.valueOf(2700), Integer.valueOf(X1), Integer.valueOf(3250), Integer.valueOf(1))), Collections.<Integer>unmodifiableList(CollectionLiterals.<Integer>newArrayList(Integer.valueOf(30), Integer.valueOf(80), Integer.valueOf(80), Integer.valueOf(60), Integer.valueOf(0))), Collections.<String>unmodifiableList(CollectionLiterals.<String>newArrayList("A", "B", "C", "D", "E", "F")), 2);
      Question _question_3 = ScanExamXtendFactory.question("EX1_Q3", Collections.<Integer>unmodifiableList(CollectionLiterals.<Integer>newArrayList(Integer.valueOf(X0), Integer.valueOf(300), Integer.valueOf(X1), Integer.valueOf(950), Integer.valueOf(2))), Collections.<Integer>unmodifiableList(CollectionLiterals.<Integer>newArrayList(Integer.valueOf(30), Integer.valueOf(80), Integer.valueOf(80), Integer.valueOf(60), Integer.valueOf(0))), Collections.<String>unmodifiableList(CollectionLiterals.<String>newArrayList("A", "B", "C", "D", "E", "F")), 2);
      Question _question_4 = ScanExamXtendFactory.question("EX2_Q1", Collections.<Integer>unmodifiableList(CollectionLiterals.<Integer>newArrayList(Integer.valueOf(X0), Integer.valueOf(2100), Integer.valueOf(X1), Integer.valueOf(2600), Integer.valueOf(2))), Collections.<Integer>unmodifiableList(CollectionLiterals.<Integer>newArrayList(Integer.valueOf(30), Integer.valueOf(80), Integer.valueOf(80), Integer.valueOf(60), Integer.valueOf(0))), Collections.<String>unmodifiableList(CollectionLiterals.<String>newArrayList("A", "B", "C", "D", "E", "F")), 2);
      Question _question_5 = ScanExamXtendFactory.question("EX2_Q2", Collections.<Integer>unmodifiableList(CollectionLiterals.<Integer>newArrayList(Integer.valueOf(X0), Integer.valueOf(2500), Integer.valueOf(X1), Integer.valueOf(3050), Integer.valueOf(2))), Collections.<Integer>unmodifiableList(CollectionLiterals.<Integer>newArrayList(Integer.valueOf(30), Integer.valueOf(80), Integer.valueOf(80), Integer.valueOf(60), Integer.valueOf(0))), Collections.<String>unmodifiableList(CollectionLiterals.<String>newArrayList("A", "B", "C", "D", "E", "F")), 2);
      Question _question_6 = ScanExamXtendFactory.question("EX2_Q3", Collections.<Integer>unmodifiableList(CollectionLiterals.<Integer>newArrayList(Integer.valueOf(X0), Integer.valueOf(100), Integer.valueOf(X1), Integer.valueOf(2400), Integer.valueOf(3))), Collections.<Integer>unmodifiableList(CollectionLiterals.<Integer>newArrayList(Integer.valueOf(30), Integer.valueOf(80), Integer.valueOf(80), Integer.valueOf(60), Integer.valueOf(0))), Collections.<String>unmodifiableList(CollectionLiterals.<String>newArrayList("A", "B", "C", "D", "E", "F")), 2);
      Question _question_7 = ScanExamXtendFactory.question("EX2_Q4", Collections.<Integer>unmodifiableList(CollectionLiterals.<Integer>newArrayList(Integer.valueOf(X0), Integer.valueOf(2500), Integer.valueOf(X1), Integer.valueOf(3300), Integer.valueOf(3))), Collections.<Integer>unmodifiableList(CollectionLiterals.<Integer>newArrayList(Integer.valueOf(30), Integer.valueOf(80), Integer.valueOf(80), Integer.valueOf(60), Integer.valueOf(0))), Collections.<String>unmodifiableList(CollectionLiterals.<String>newArrayList("A", "B", "C", "D", "E", "F")), 2);
      Question _question_8 = ScanExamXtendFactory.question("EX2_Q5", Collections.<Integer>unmodifiableList(CollectionLiterals.<Integer>newArrayList(Integer.valueOf(X0), Integer.valueOf(450), Integer.valueOf(X1), Integer.valueOf(1000), Integer.valueOf(4))), Collections.<Integer>unmodifiableList(CollectionLiterals.<Integer>newArrayList(Integer.valueOf(30), Integer.valueOf(80), Integer.valueOf(80), Integer.valueOf(60), Integer.valueOf(0))), Collections.<String>unmodifiableList(CollectionLiterals.<String>newArrayList("A", "B", "C", "D", "E", "F")), 2);
      Question _question_9 = ScanExamXtendFactory.question("EX2_Q6", Collections.<Integer>unmodifiableList(CollectionLiterals.<Integer>newArrayList(Integer.valueOf(X0), Integer.valueOf(1000), Integer.valueOf(X1), Integer.valueOf(1500), Integer.valueOf(4))), Collections.<Integer>unmodifiableList(CollectionLiterals.<Integer>newArrayList(Integer.valueOf(30), Integer.valueOf(80), Integer.valueOf(80), Integer.valueOf(60), Integer.valueOf(0))), Collections.<String>unmodifiableList(CollectionLiterals.<String>newArrayList("A", "B", "C", "D", "E", "F")), 2);
      Question _question_10 = ScanExamXtendFactory.question("EX2_Q7", Collections.<Integer>unmodifiableList(CollectionLiterals.<Integer>newArrayList(Integer.valueOf(X0), Integer.valueOf(1550), Integer.valueOf(X1), Integer.valueOf(2400), Integer.valueOf(4))), Collections.<Integer>unmodifiableList(CollectionLiterals.<Integer>newArrayList(Integer.valueOf(30), Integer.valueOf(80), Integer.valueOf(80), Integer.valueOf(60), Integer.valueOf(0))), Collections.<String>unmodifiableList(CollectionLiterals.<String>newArrayList("A", "B", "C", "D", "E", "F")), 2);
      Question _question_11 = ScanExamXtendFactory.question("EX2_Q8", Collections.<Integer>unmodifiableList(CollectionLiterals.<Integer>newArrayList(Integer.valueOf(X0), Integer.valueOf(2300), Integer.valueOf(X1), Integer.valueOf(2800), Integer.valueOf(4))), Collections.<Integer>unmodifiableList(CollectionLiterals.<Integer>newArrayList(Integer.valueOf(30), Integer.valueOf(80), Integer.valueOf(80), Integer.valueOf(60), Integer.valueOf(0))), Collections.<String>unmodifiableList(CollectionLiterals.<String>newArrayList("A", "B", "C", "D", "E", "F")), 2);
      Question _question_12 = ScanExamXtendFactory.question("EX2_Q9", Collections.<Integer>unmodifiableList(CollectionLiterals.<Integer>newArrayList(Integer.valueOf(X0), Integer.valueOf(2700), Integer.valueOf(X1), Integer.valueOf(3250), Integer.valueOf(4))), Collections.<Integer>unmodifiableList(CollectionLiterals.<Integer>newArrayList(Integer.valueOf(30), Integer.valueOf(80), Integer.valueOf(80), Integer.valueOf(60), Integer.valueOf(0))), Collections.<String>unmodifiableList(CollectionLiterals.<String>newArrayList("A", "B", "C", "D", "E", "F")), 2);
      Question _question_13 = ScanExamXtendFactory.question("EX3_Q1", Collections.<Integer>unmodifiableList(CollectionLiterals.<Integer>newArrayList(Integer.valueOf(X0), Integer.valueOf(1300), Integer.valueOf(X1), Integer.valueOf(1800), Integer.valueOf(5))), Collections.<Integer>unmodifiableList(CollectionLiterals.<Integer>newArrayList(Integer.valueOf(30), Integer.valueOf(80), Integer.valueOf(80), Integer.valueOf(60), Integer.valueOf(0))), Collections.<String>unmodifiableList(CollectionLiterals.<String>newArrayList("A", "B", "C", "D", "E", "F")), 2);
      Question _question_14 = ScanExamXtendFactory.question("EX3_Q2", Collections.<Integer>unmodifiableList(CollectionLiterals.<Integer>newArrayList(Integer.valueOf(X0), Integer.valueOf(1700), Integer.valueOf(X1), Integer.valueOf(2100), Integer.valueOf(5))), Collections.<Integer>unmodifiableList(CollectionLiterals.<Integer>newArrayList(Integer.valueOf(30), Integer.valueOf(80), Integer.valueOf(80), Integer.valueOf(60), Integer.valueOf(0))), Collections.<String>unmodifiableList(CollectionLiterals.<String>newArrayList("A", "B", "C", "D", "E", "F")), 2);
      Question _question_15 = ScanExamXtendFactory.question("EX3_Q3", Collections.<Integer>unmodifiableList(CollectionLiterals.<Integer>newArrayList(Integer.valueOf(X0), Integer.valueOf(0), Integer.valueOf(X1), Integer.valueOf(3150), Integer.valueOf(5))), Collections.<Integer>unmodifiableList(CollectionLiterals.<Integer>newArrayList(Integer.valueOf(30), Integer.valueOf(80), Integer.valueOf(80), Integer.valueOf(60), Integer.valueOf(0))), Collections.<String>unmodifiableList(CollectionLiterals.<String>newArrayList("A", "B", "C", "D", "E", "F")), 5);
      final Exam e = ScanExamXtendFactory.exam(
        "DS_CCI", 
        "./CopieScanOSentieys/png", 
        6, 
        42, 
        Collections.<Question>unmodifiableList(CollectionLiterals.<Question>newArrayList(_question, _question_1, _question_2, _question_3, _question_4, _question_5, _question_6, _question_7, _question_8, _question_9, _question_10, _question_11, _question_12, _question_13, _question_14, _question_15)));
      final List<Integer> weights = Collections.<Integer>unmodifiableList(CollectionLiterals.<Integer>newArrayList(Integer.valueOf(0), Integer.valueOf(1), Integer.valueOf(2), Integer.valueOf(2), Integer.valueOf(1), Integer.valueOf(6), Integer.valueOf(3), Integer.valueOf(6), Integer.valueOf(2), Integer.valueOf(2), Integer.valueOf(2), Integer.valueOf(9), Integer.valueOf(10), Integer.valueOf(4), Integer.valueOf(3), Integer.valueOf(6)));
      int _size = e.getQuestions().size();
      ExclusiveRange _doubleDotLessThan = new ExclusiveRange(0, _size, true);
      for (final Integer i : _doubleDotLessThan) {
        Question _get = e.getQuestions().get((i).intValue());
        _get.setWeight((weights.get((i).intValue())).intValue());
      }
      _xblockexpression = e;
    }
    return _xblockexpression;
  }
  
  public static Exam december19() {
    Exam _xblockexpression = null;
    {
      final int X0 = 100;
      final int X1 = 2450;
      Question _question = ScanExamXtendFactory.question("ID", Collections.<Integer>unmodifiableList(CollectionLiterals.<Integer>newArrayList(Integer.valueOf(X0), Integer.valueOf(0), Integer.valueOf(X1), Integer.valueOf(400), Integer.valueOf(1))), Collections.<Integer>unmodifiableList(CollectionLiterals.<Integer>newArrayList(Integer.valueOf(30), Integer.valueOf(80), Integer.valueOf(80), Integer.valueOf(60), Integer.valueOf(0))), Collections.<String>unmodifiableList(CollectionLiterals.<String>newArrayList("0")), 1);
      Question _question_1 = ScanExamXtendFactory.question("EX1_Q1", Collections.<Integer>unmodifiableList(CollectionLiterals.<Integer>newArrayList(Integer.valueOf(X0), Integer.valueOf(2400), Integer.valueOf(X1), Integer.valueOf(2750), Integer.valueOf(1))), Collections.<Integer>unmodifiableList(CollectionLiterals.<Integer>newArrayList(Integer.valueOf(30), Integer.valueOf(80), Integer.valueOf(80), Integer.valueOf(60), Integer.valueOf(0))), Collections.<String>unmodifiableList(CollectionLiterals.<String>newArrayList("F", "A")), 1);
      Question _question_2 = ScanExamXtendFactory.question("EX1_Q2", Collections.<Integer>unmodifiableList(CollectionLiterals.<Integer>newArrayList(Integer.valueOf(X0), Integer.valueOf(1600), Integer.valueOf(X1), Integer.valueOf(3200), Integer.valueOf(1))), Collections.<Integer>unmodifiableList(CollectionLiterals.<Integer>newArrayList(Integer.valueOf(30), Integer.valueOf(80), Integer.valueOf(80), Integer.valueOf(60), Integer.valueOf(0))), Collections.<String>unmodifiableList(CollectionLiterals.<String>newArrayList("F", "C", "A")), 2);
      Question _question_3 = ScanExamXtendFactory.question("EX1_Q3", Collections.<Integer>unmodifiableList(CollectionLiterals.<Integer>newArrayList(Integer.valueOf(X0), Integer.valueOf(280), Integer.valueOf(X1), Integer.valueOf(650), Integer.valueOf(2))), Collections.<Integer>unmodifiableList(CollectionLiterals.<Integer>newArrayList(Integer.valueOf(30), Integer.valueOf(80), Integer.valueOf(80), Integer.valueOf(60), Integer.valueOf(0))), Collections.<String>unmodifiableList(CollectionLiterals.<String>newArrayList("F", "D", "C", "B", "A")), 4);
      Question _question_4 = ScanExamXtendFactory.question("EX1_Q4", Collections.<Integer>unmodifiableList(CollectionLiterals.<Integer>newArrayList(Integer.valueOf(X0), Integer.valueOf(700), Integer.valueOf(X1), Integer.valueOf(1350), Integer.valueOf(2))), Collections.<Integer>unmodifiableList(CollectionLiterals.<Integer>newArrayList(Integer.valueOf(30), Integer.valueOf(80), Integer.valueOf(80), Integer.valueOf(60), Integer.valueOf(0))), Collections.<String>unmodifiableList(CollectionLiterals.<String>newArrayList("F", "D", "C", "B", "A")), 2);
      Question _question_5 = ScanExamXtendFactory.question("EX1_Q5", Collections.<Integer>unmodifiableList(CollectionLiterals.<Integer>newArrayList(Integer.valueOf(X0), Integer.valueOf(1450), Integer.valueOf(X1), Integer.valueOf(2200), Integer.valueOf(2))), Collections.<Integer>unmodifiableList(CollectionLiterals.<Integer>newArrayList(Integer.valueOf(30), Integer.valueOf(80), Integer.valueOf(80), Integer.valueOf(60), Integer.valueOf(0))), Collections.<String>unmodifiableList(CollectionLiterals.<String>newArrayList("A", "B", "C", "D", "E", "F")), 2);
      Question _question_6 = ScanExamXtendFactory.question("EX1_Q6", Collections.<Integer>unmodifiableList(CollectionLiterals.<Integer>newArrayList(Integer.valueOf(X0), Integer.valueOf(2275), Integer.valueOf(X1), Integer.valueOf(3000), Integer.valueOf(2))), Collections.<Integer>unmodifiableList(CollectionLiterals.<Integer>newArrayList(Integer.valueOf(30), Integer.valueOf(80), Integer.valueOf(80), Integer.valueOf(60), Integer.valueOf(0))), Collections.<String>unmodifiableList(CollectionLiterals.<String>newArrayList("A", "B", "C", "D", "E", "F")), 2);
      Question _question_7 = ScanExamXtendFactory.question("EX1_Q7", Collections.<Integer>unmodifiableList(CollectionLiterals.<Integer>newArrayList(Integer.valueOf(X0), Integer.valueOf(3000), Integer.valueOf(X1), Integer.valueOf(3170), Integer.valueOf(2))), Collections.<Integer>unmodifiableList(CollectionLiterals.<Integer>newArrayList(Integer.valueOf(30), Integer.valueOf(80), Integer.valueOf(80), Integer.valueOf(60), Integer.valueOf(0))), Collections.<String>unmodifiableList(CollectionLiterals.<String>newArrayList("F", "A")), 1);
      Question _question_8 = ScanExamXtendFactory.question("EX2_Q1", Collections.<Integer>unmodifiableList(CollectionLiterals.<Integer>newArrayList(Integer.valueOf(X0), Integer.valueOf(2350), Integer.valueOf(X1), Integer.valueOf(3300), Integer.valueOf(3))), Collections.<Integer>unmodifiableList(CollectionLiterals.<Integer>newArrayList(Integer.valueOf(30), Integer.valueOf(80), Integer.valueOf(80), Integer.valueOf(60), Integer.valueOf(0))), Collections.<String>unmodifiableList(CollectionLiterals.<String>newArrayList("A", "B", "C", "D", "E", "F")), 2);
      Question _question_9 = ScanExamXtendFactory.question("EX2_Q2", Collections.<Integer>unmodifiableList(CollectionLiterals.<Integer>newArrayList(Integer.valueOf(X0), Integer.valueOf(500), Integer.valueOf(X1), Integer.valueOf(1900), Integer.valueOf(4))), Collections.<Integer>unmodifiableList(CollectionLiterals.<Integer>newArrayList(Integer.valueOf(30), Integer.valueOf(80), Integer.valueOf(80), Integer.valueOf(60), Integer.valueOf(0))), Collections.<String>unmodifiableList(CollectionLiterals.<String>newArrayList("A", "B", "C", "D", "E", "F")), 2);
      Question _question_10 = ScanExamXtendFactory.question("EX2_Q3", Collections.<Integer>unmodifiableList(CollectionLiterals.<Integer>newArrayList(Integer.valueOf(X0), Integer.valueOf(2100), Integer.valueOf(X1), Integer.valueOf(3000), Integer.valueOf(4))), Collections.<Integer>unmodifiableList(CollectionLiterals.<Integer>newArrayList(Integer.valueOf(30), Integer.valueOf(80), Integer.valueOf(80), Integer.valueOf(60), Integer.valueOf(0))), Collections.<String>unmodifiableList(CollectionLiterals.<String>newArrayList("A", "B", "C", "D", "E", "F")), 2);
      Question _question_11 = ScanExamXtendFactory.question("EX2_Q4", Collections.<Integer>unmodifiableList(CollectionLiterals.<Integer>newArrayList(Integer.valueOf(X0), Integer.valueOf(450), Integer.valueOf(X1), Integer.valueOf(1800), Integer.valueOf(5))), Collections.<Integer>unmodifiableList(CollectionLiterals.<Integer>newArrayList(Integer.valueOf(30), Integer.valueOf(80), Integer.valueOf(80), Integer.valueOf(60), Integer.valueOf(0))), Collections.<String>unmodifiableList(CollectionLiterals.<String>newArrayList("A", "B", "C", "D", "E", "F")), 2);
      Question _question_12 = ScanExamXtendFactory.question("EX2_Q5", Collections.<Integer>unmodifiableList(CollectionLiterals.<Integer>newArrayList(Integer.valueOf(X0), Integer.valueOf(2000), Integer.valueOf(X1), Integer.valueOf(3000), Integer.valueOf(5))), Collections.<Integer>unmodifiableList(CollectionLiterals.<Integer>newArrayList(Integer.valueOf(30), Integer.valueOf(80), Integer.valueOf(80), Integer.valueOf(60), Integer.valueOf(0))), Collections.<String>unmodifiableList(CollectionLiterals.<String>newArrayList("A", "B", "C", "D", "E", "F")), 5);
      Question _question_13 = ScanExamXtendFactory.question("EX3_Q1", Collections.<Integer>unmodifiableList(CollectionLiterals.<Integer>newArrayList(Integer.valueOf(X0), Integer.valueOf(500), Integer.valueOf(X1), Integer.valueOf(1050), Integer.valueOf(6))), Collections.<Integer>unmodifiableList(CollectionLiterals.<Integer>newArrayList(Integer.valueOf(30), Integer.valueOf(80), Integer.valueOf(80), Integer.valueOf(60), Integer.valueOf(0))), Collections.<String>unmodifiableList(CollectionLiterals.<String>newArrayList("A", "B", "C", "D", "E", "F")), 2);
      Question _question_14 = ScanExamXtendFactory.question("EX3_Q2a", Collections.<Integer>unmodifiableList(CollectionLiterals.<Integer>newArrayList(Integer.valueOf(X0), Integer.valueOf(1450), Integer.valueOf(X1), Integer.valueOf(1900), Integer.valueOf(6))), Collections.<Integer>unmodifiableList(CollectionLiterals.<Integer>newArrayList(Integer.valueOf(30), Integer.valueOf(80), Integer.valueOf(80), Integer.valueOf(60), Integer.valueOf(0))), Collections.<String>unmodifiableList(CollectionLiterals.<String>newArrayList("A", "B", "C", "D", "E", "F")), 2);
      Question _question_15 = ScanExamXtendFactory.question("EX3_Q2b", Collections.<Integer>unmodifiableList(CollectionLiterals.<Integer>newArrayList(Integer.valueOf(X0), Integer.valueOf(1900), Integer.valueOf(X1), Integer.valueOf(3250), Integer.valueOf(6))), Collections.<Integer>unmodifiableList(CollectionLiterals.<Integer>newArrayList(Integer.valueOf(30), Integer.valueOf(80), Integer.valueOf(80), Integer.valueOf(60), Integer.valueOf(0))), Collections.<String>unmodifiableList(CollectionLiterals.<String>newArrayList("A", "B", "C", "D", "E", "F")), 2);
      final Exam e = ScanExamXtendFactory.exam(
        "PFO_december_19", 
        "./examples/scan/", 
        6, 
        42, 
        Collections.<Question>unmodifiableList(CollectionLiterals.<Question>newArrayList(_question, _question_1, _question_2, _question_3, _question_4, _question_5, _question_6, _question_7, _question_8, _question_9, _question_10, _question_11, _question_12, _question_13, _question_14, _question_15)));
      final List<Integer> weights = Collections.<Integer>unmodifiableList(CollectionLiterals.<Integer>newArrayList(Integer.valueOf(0), Integer.valueOf(1), Integer.valueOf(2), Integer.valueOf(2), Integer.valueOf(2), Integer.valueOf(2), Integer.valueOf(4), Integer.valueOf(1), Integer.valueOf(2), Integer.valueOf(6), Integer.valueOf(3), Integer.valueOf(6), Integer.valueOf(2), Integer.valueOf(4), Integer.valueOf(3), Integer.valueOf(6)));
      int _size = e.getQuestions().size();
      ExclusiveRange _doubleDotLessThan = new ExclusiveRange(0, _size, true);
      for (final Integer i : _doubleDotLessThan) {
        Question _get = e.getQuestions().get((i).intValue());
        _get.setWeight((weights.get((i).intValue())).intValue());
      }
      _xblockexpression = e;
    }
    return _xblockexpression;
  }
  
  public static void main(final String[] args) {
    try {
      final Exam dec19 = PFOExams.december19();
      String _label = dec19.getLabel();
      String _plus = ("examples/" + _label);
      String _plus_1 = (_plus + ".xmi");
      ExamIO.save(dec19, _plus_1);
      final Exam eii = PFOExams.olivier();
      String _label_1 = eii.getLabel();
      String _plus_2 = ("examples/" + _label_1);
      String _plus_3 = (_plus_2 + ".xmi");
      ExamIO.save(eii, _plus_3);
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
}
