package fr.istic.tools.scanexam.instances;

import fr.istic.tools.scanexam.Exam;
import fr.istic.tools.scanexam.Question;
import fr.istic.tools.scanexam.utils.ScanExamXtendFactory;
import java.util.Collections;
import java.util.List;
import org.eclipse.xtext.xbase.lib.CollectionLiterals;
import org.eclipse.xtext.xbase.lib.ExclusiveRange;

@SuppressWarnings("all")
public class PFOExams {
  public static Exam december19() {
    Exam _xblockexpression = null;
    {
      final int X0 = 100;
      final int X1 = 2450;
      Question _question = ScanExamXtendFactory.question("EX1_Q1", Collections.<Integer>unmodifiableList(CollectionLiterals.<Integer>newArrayList(Integer.valueOf(X0), Integer.valueOf(2400), Integer.valueOf(X1), Integer.valueOf(2750), Integer.valueOf(1))), Collections.<Integer>unmodifiableList(CollectionLiterals.<Integer>newArrayList(Integer.valueOf(30), Integer.valueOf(80), Integer.valueOf(80), Integer.valueOf(60), Integer.valueOf(0))), Collections.<String>unmodifiableList(CollectionLiterals.<String>newArrayList("F", "A")), 1);
      Question _question_1 = ScanExamXtendFactory.question("EX1_Q2", Collections.<Integer>unmodifiableList(CollectionLiterals.<Integer>newArrayList(Integer.valueOf(X0), Integer.valueOf(1600), Integer.valueOf(X1), Integer.valueOf(3200), Integer.valueOf(1))), Collections.<Integer>unmodifiableList(CollectionLiterals.<Integer>newArrayList(Integer.valueOf(30), Integer.valueOf(80), Integer.valueOf(80), Integer.valueOf(60), Integer.valueOf(0))), Collections.<String>unmodifiableList(CollectionLiterals.<String>newArrayList("F", "C", "A")), 2);
      Question _question_2 = ScanExamXtendFactory.question("EX1_Q3", Collections.<Integer>unmodifiableList(CollectionLiterals.<Integer>newArrayList(Integer.valueOf(X0), Integer.valueOf(280), Integer.valueOf(X1), Integer.valueOf(650), Integer.valueOf(2))), Collections.<Integer>unmodifiableList(CollectionLiterals.<Integer>newArrayList(Integer.valueOf(30), Integer.valueOf(80), Integer.valueOf(80), Integer.valueOf(60), Integer.valueOf(0))), Collections.<String>unmodifiableList(CollectionLiterals.<String>newArrayList("F", "D", "C", "B", "A")), 4);
      Question _question_3 = ScanExamXtendFactory.question("EX1_Q4", Collections.<Integer>unmodifiableList(CollectionLiterals.<Integer>newArrayList(Integer.valueOf(X0), Integer.valueOf(700), Integer.valueOf(X1), Integer.valueOf(1350), Integer.valueOf(2))), Collections.<Integer>unmodifiableList(CollectionLiterals.<Integer>newArrayList(Integer.valueOf(30), Integer.valueOf(80), Integer.valueOf(80), Integer.valueOf(60), Integer.valueOf(0))), Collections.<String>unmodifiableList(CollectionLiterals.<String>newArrayList("F", "D", "C", "B", "A")), 2);
      Question _question_4 = ScanExamXtendFactory.question("EX1_Q5", Collections.<Integer>unmodifiableList(CollectionLiterals.<Integer>newArrayList(Integer.valueOf(X0), Integer.valueOf(1450), Integer.valueOf(X1), Integer.valueOf(2200), Integer.valueOf(2))), Collections.<Integer>unmodifiableList(CollectionLiterals.<Integer>newArrayList(Integer.valueOf(30), Integer.valueOf(80), Integer.valueOf(80), Integer.valueOf(60), Integer.valueOf(0))), Collections.<String>unmodifiableList(CollectionLiterals.<String>newArrayList("A", "B", "C", "D", "E", "F")), 2);
      Question _question_5 = ScanExamXtendFactory.question("EX1_Q6", Collections.<Integer>unmodifiableList(CollectionLiterals.<Integer>newArrayList(Integer.valueOf(X0), Integer.valueOf(2275), Integer.valueOf(X1), Integer.valueOf(3000), Integer.valueOf(2))), Collections.<Integer>unmodifiableList(CollectionLiterals.<Integer>newArrayList(Integer.valueOf(30), Integer.valueOf(80), Integer.valueOf(80), Integer.valueOf(60), Integer.valueOf(0))), Collections.<String>unmodifiableList(CollectionLiterals.<String>newArrayList("A", "B", "C", "D", "E", "F")), 2);
      Question _question_6 = ScanExamXtendFactory.question("EX1_Q7", Collections.<Integer>unmodifiableList(CollectionLiterals.<Integer>newArrayList(Integer.valueOf(X0), Integer.valueOf(3000), Integer.valueOf(X1), Integer.valueOf(3170), Integer.valueOf(2))), Collections.<Integer>unmodifiableList(CollectionLiterals.<Integer>newArrayList(Integer.valueOf(30), Integer.valueOf(80), Integer.valueOf(80), Integer.valueOf(60), Integer.valueOf(0))), Collections.<String>unmodifiableList(CollectionLiterals.<String>newArrayList("F", "A")), 1);
      Question _question_7 = ScanExamXtendFactory.question("EX2_Q1", Collections.<Integer>unmodifiableList(CollectionLiterals.<Integer>newArrayList(Integer.valueOf(X0), Integer.valueOf(2350), Integer.valueOf(X1), Integer.valueOf(3300), Integer.valueOf(3))), Collections.<Integer>unmodifiableList(CollectionLiterals.<Integer>newArrayList(Integer.valueOf(30), Integer.valueOf(80), Integer.valueOf(80), Integer.valueOf(60), Integer.valueOf(0))), Collections.<String>unmodifiableList(CollectionLiterals.<String>newArrayList("A", "B", "C", "D", "E", "F")), 2);
      Question _question_8 = ScanExamXtendFactory.question("EX2_Q2", Collections.<Integer>unmodifiableList(CollectionLiterals.<Integer>newArrayList(Integer.valueOf(X0), Integer.valueOf(500), Integer.valueOf(X1), Integer.valueOf(1900), Integer.valueOf(4))), Collections.<Integer>unmodifiableList(CollectionLiterals.<Integer>newArrayList(Integer.valueOf(30), Integer.valueOf(80), Integer.valueOf(80), Integer.valueOf(60), Integer.valueOf(0))), Collections.<String>unmodifiableList(CollectionLiterals.<String>newArrayList("A", "B", "C", "D", "E", "F")), 2);
      Question _question_9 = ScanExamXtendFactory.question("EX2_Q3", Collections.<Integer>unmodifiableList(CollectionLiterals.<Integer>newArrayList(Integer.valueOf(X0), Integer.valueOf(2100), Integer.valueOf(X1), Integer.valueOf(3000), Integer.valueOf(4))), Collections.<Integer>unmodifiableList(CollectionLiterals.<Integer>newArrayList(Integer.valueOf(30), Integer.valueOf(80), Integer.valueOf(80), Integer.valueOf(60), Integer.valueOf(0))), Collections.<String>unmodifiableList(CollectionLiterals.<String>newArrayList("A", "B", "C", "D", "E", "F")), 2);
      Question _question_10 = ScanExamXtendFactory.question("EX2_Q4", Collections.<Integer>unmodifiableList(CollectionLiterals.<Integer>newArrayList(Integer.valueOf(X0), Integer.valueOf(450), Integer.valueOf(X1), Integer.valueOf(1800), Integer.valueOf(5))), Collections.<Integer>unmodifiableList(CollectionLiterals.<Integer>newArrayList(Integer.valueOf(30), Integer.valueOf(80), Integer.valueOf(80), Integer.valueOf(60), Integer.valueOf(0))), Collections.<String>unmodifiableList(CollectionLiterals.<String>newArrayList("A", "B", "C", "D", "E", "F")), 2);
      Question _question_11 = ScanExamXtendFactory.question("EX2_Q5", Collections.<Integer>unmodifiableList(CollectionLiterals.<Integer>newArrayList(Integer.valueOf(X0), Integer.valueOf(2000), Integer.valueOf(X1), Integer.valueOf(3000), Integer.valueOf(5))), Collections.<Integer>unmodifiableList(CollectionLiterals.<Integer>newArrayList(Integer.valueOf(30), Integer.valueOf(80), Integer.valueOf(80), Integer.valueOf(60), Integer.valueOf(0))), Collections.<String>unmodifiableList(CollectionLiterals.<String>newArrayList("A", "B", "C", "D", "E", "F")), 5);
      Question _question_12 = ScanExamXtendFactory.question("EX3_Q1", Collections.<Integer>unmodifiableList(CollectionLiterals.<Integer>newArrayList(Integer.valueOf(X0), Integer.valueOf(500), Integer.valueOf(X1), Integer.valueOf(1050), Integer.valueOf(6))), Collections.<Integer>unmodifiableList(CollectionLiterals.<Integer>newArrayList(Integer.valueOf(30), Integer.valueOf(80), Integer.valueOf(80), Integer.valueOf(60), Integer.valueOf(0))), Collections.<String>unmodifiableList(CollectionLiterals.<String>newArrayList("A", "B", "C", "D", "E", "F")), 2);
      Question _question_13 = ScanExamXtendFactory.question("EX3_Q2a", Collections.<Integer>unmodifiableList(CollectionLiterals.<Integer>newArrayList(Integer.valueOf(X0), Integer.valueOf(1450), Integer.valueOf(X1), Integer.valueOf(1900), Integer.valueOf(6))), Collections.<Integer>unmodifiableList(CollectionLiterals.<Integer>newArrayList(Integer.valueOf(30), Integer.valueOf(80), Integer.valueOf(80), Integer.valueOf(60), Integer.valueOf(0))), Collections.<String>unmodifiableList(CollectionLiterals.<String>newArrayList("A", "B", "C", "D", "E", "F")), 2);
      Question _question_14 = ScanExamXtendFactory.question("EX3_Q2b", Collections.<Integer>unmodifiableList(CollectionLiterals.<Integer>newArrayList(Integer.valueOf(X0), Integer.valueOf(1900), Integer.valueOf(X1), Integer.valueOf(3250), Integer.valueOf(6))), Collections.<Integer>unmodifiableList(CollectionLiterals.<Integer>newArrayList(Integer.valueOf(30), Integer.valueOf(80), Integer.valueOf(80), Integer.valueOf(60), Integer.valueOf(0))), Collections.<String>unmodifiableList(CollectionLiterals.<String>newArrayList("A", "B", "C", "D", "E", "F")), 2);
      final Exam e = ScanExamXtendFactory.exam(
        "PFO_december_19", 
        "/Users/sderrien/Documents/IFSIC/2019-2020/PFO/Examen/dec19/CopiesScan/png", 
        6, 
        Collections.<Question>unmodifiableList(CollectionLiterals.<Question>newArrayList(_question, _question_1, _question_2, _question_3, _question_4, _question_5, _question_6, _question_7, _question_8, _question_9, _question_10, _question_11, _question_12, _question_13, _question_14)));
      final List<Integer> weights = Collections.<Integer>unmodifiableList(CollectionLiterals.<Integer>newArrayList(Integer.valueOf(1), Integer.valueOf(2), Integer.valueOf(2), Integer.valueOf(2), Integer.valueOf(2), Integer.valueOf(4), Integer.valueOf(1), Integer.valueOf(2), Integer.valueOf(6), Integer.valueOf(3), Integer.valueOf(6), Integer.valueOf(2), Integer.valueOf(4), Integer.valueOf(4), Integer.valueOf(6)));
      int _size = e.getQuestions().size();
      ExclusiveRange _doubleDotLessThan = new ExclusiveRange(0, _size, true);
      for (final Integer i : _doubleDotLessThan) {
        Question _get = e.getQuestions().get((i).intValue());
        _get.setWeight((weights.get((i).intValue())).intValue());
      }
      _xblockexpression = e;
    }
    return _xblockexpression;
  }
}
